# Generated by Django 4.2 on 2023-05-04 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='fpe',
            field=models.FileField(blank=True, null=True, upload_to='FPE', verbose_name='fiche de presentation'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='programmes.matiere'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='Cours en pdf'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='chapitre no'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Video', verbose_name='cours en Video'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiere_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
