# Generated by Django 4.2.1 on 2023-05-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsAndEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("summary", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "posted_as",
                    models.CharField(
                        choices=[("News", "News"), ("Event", "Event")], max_length=10
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
